"""
LLM Client Wrapper for AI Expense & Budget Management System.
Handles communication with OpenAI API using environment variables.
"""

import os
from typing import Optional
from dotenv import load_dotenv
from openai import OpenAI, OpenAIError

# Load environment variables from .env file if present
load_dotenv()


def get_openai_client() -> OpenAI:
    """
    Instantiates and returns an OpenAI client instance.
    Validates that the OPENAI_API_KEY environment variable is present.
    """
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key or api_key.strip() == "" or "your_openai_api_key_here" in api_key:
        raise ValueError(
            "OPENAI_API_KEY environment variable is missing or invalid. "
            "Please set a valid API key in your .env file or environment."
        )

    # Optional custom base url if configured in environment
    base_url = os.getenv("OPENAI_BASE_URL")
    if base_url and base_url.strip():
        return OpenAI(api_key=api_key.strip(), base_url=base_url.strip())

    return OpenAI(api_key=api_key.strip())


def get_llm_response(system_prompt: str, user_prompt: str) -> str:
    """
    Sends a system prompt and user prompt to the configured OpenAI model,
    and returns the text response.

    Parameters:
        system_prompt (str): System prompt giving instructions to the LLM.
        user_prompt (str): User input prompt or data context.

    Returns:
        str: Response text generated by the LLM model.
    """
    try:
        client = get_openai_client()
        model_name = os.getenv("OPENAI_MODEL", "gpt-4o-mini")

        response = client.chat.completions.create(
            model=model_name,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            temperature=0.7,
        )

        if response.choices and len(response.choices) > 0:
            content = response.choices[0].message.content
            return content.strip() if content else ""

        return "No response content returned by the AI model."

    except ValueError as ve:
        # Re-raise user configuration errors
        return f"Configuration Error: {str(ve)}"
    except OpenAIError as oe:
        # Catch OpenAI specific API errors
        return f"OpenAI API Error: {str(oe)}"
    except Exception as e:
        # Catch unexpected errors gracefully
        return f"Unexpected Error while calling LLM: {str(e)}"
